// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzWalksAPI.Data;

#nullable disable

namespace NzWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20240523165602_CreateImagesTable")]
    partial class CreateImagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NzWalksAPI.Domain.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afcc9581-dcb9-4096-916a-fbed178c3821"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("f57e2c5d-2b32-490a-bfb2-d5a4b0d113cb"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("cfd30386-d2c9-4fd1-8646-51b02bdb3c17"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NzWalksAPI.Domain.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NzWalksAPI.Domain.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c4d772e-27fa-4247-c199-08dc7985bde5"),
                            Code = "WLG",
                            ImageUrl = "https://fastly.picsum.photos/id/1001/800/600.jpg?hmac=SYMSTZ_jGTLCAYO7vGHOck2TiSy2qjo6OPHwBGNem0I",
                            Name = "Wellington Region"
                        },
                        new
                        {
                            Id = new Guid("63e99d9b-a915-4d21-1025-08dc7989d7f2"),
                            Code = "QLS",
                            ImageUrl = "https://fastly.picsum.photos/id/176/800/600.jpg?hmac=dGLT-aXDtvYjsZo8E4Vp7osGVQ_z0Gw0BomVl52uU5o",
                            Name = "Queenstown Region"
                        },
                        new
                        {
                            Id = new Guid("b517a10d-2e08-4031-9c6b-b26e77560c36"),
                            Code = "AKL",
                            ImageUrl = "https://fastly.picsum.photos/id/337/800/600.jpg?hmac=Gx8pjhwU87sYnp2K9YBi3hvR78dBeAUbrVF6KJCwGJA",
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = new Guid("3da94be2-f663-4e18-8843-ede475618c77"),
                            Code = "STL",
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("NzWalksAPI.Domain.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NzWalksAPI.Domain.Domain.Walk", b =>
                {
                    b.HasOne("NzWalksAPI.Domain.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NzWalksAPI.Domain.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
